name: Components
favicon: null
layout_spectrum: 0.23826
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#e2536b'
    - '#e2e2e2'
    - '#53b2e2'
    - '#3d738d'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
